# Day 24 third attempt

In [1]:
import pandas as pd
from pathlib import Path
import io

In [2]:
# So it turns out that the input code repoeats itself every 18 instructions
program = Path("input.txt").read_text().splitlines()
chunks = []
for i in range(0,len(program),18):
    chunks.append(",".join(program[i:i+18]))
text = "\n".join(chunks)
df = pd.read_csv(io.StringIO(text), header=None)

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,inp w,mul x 0,add x z,mod x 26,div z 1,add x 12,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 7,mul y x,add z y
1,inp w,mul x 0,add x z,mod x 26,div z 1,add x 11,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 15,mul y x,add z y
2,inp w,mul x 0,add x z,mod x 26,div z 1,add x 12,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 2,mul y x,add z y
3,inp w,mul x 0,add x z,mod x 26,div z 26,add x -3,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 15,mul y x,add z y
4,inp w,mul x 0,add x z,mod x 26,div z 1,add x 10,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 14,mul y x,add z y
5,inp w,mul x 0,add x z,mod x 26,div z 26,add x -9,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 2,mul y x,add z y
6,inp w,mul x 0,add x z,mod x 26,div z 1,add x 10,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 15,mul y x,add z y
7,inp w,mul x 0,add x z,mod x 26,div z 26,add x -7,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 1,mul y x,add z y
8,inp w,mul x 0,add x z,mod x 26,div z 26,add x -11,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 15,mul y x,add z y
9,inp w,mul x 0,add x z,mod x 26,div z 26,add x -4,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 15,mul y x,add z y
10,inp w,mul x 0,add x z,mod x 26,div z 1,add x 14,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 12,mul y x,add z y
11,inp w,mul x 0,add x z,mod x 26,div z 1,add x 11,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 2,mul y x,add z y
12,inp w,mul x 0,add x z,mod x 26,div z 26,add x -8,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 13,mul y x,add z y
13,inp w,mul x 0,add x z,mod x 26,div z 26,add x -10,eql x w,eql x 0,mul y 0,add y 25,mul y x,add y 1,mul z y,mul y 0,add y w,add y 13,mul y x,add z y

Based on this idea, I wrote a new code generator to clean up obfuscated code, 
and then hand-wrote functions to constrain the search space

In [4]:
from output_opt import eval_license
from search_spaces import search_space, search_space2
from tqdm import tqdm

In [5]:
for serial in tqdm(search_space()):
    if eval_license(serial):
        print(serial)
        break

43046775it [00:18, 2319367.29it/s]

(6, 5, 9, 8, 4, 9, 1, 9, 9, 9, 7, 9, 3, 9)

In [6]:
for serial in tqdm(search_space2()):
    if eval_license(serial):
        print(serial)
        break

2584550it [00:01, 1834068.81it/s]

(1, 1, 2, 1, 1, 6, 1, 9, 5, 4, 1, 7, 1, 3)